spring.application.name=voice_assistant

spring.ai.openai.api-key=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

spring.ai.openai.base-url=https://api.groq.com/openai

# CHAT MODEL
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# WHISPER MODEL
spring.ai.openai.audio.transcription.options.model=whisper-large-v3-turbo

# OPTIONAL
spring.ai.openai.audio.transcription.options.temperature=0
